- name: Installing common platform rpm files
  ansible.builtin.yum:
    name: ['nfs-utils', 'git', 'epel-release', 'sssd', 'authconfig', 'compat-openssl10', 'yum-utils', 'dos2unix']
    state: latest
    update_cache: true
