- name: Common tasks
  ansible.builtin.include_tasks: reachable.yaml
- name: Update
  ansible.builtin.include_tasks: update.yaml
- name: Common
  ansible.builtin.include_tasks: common.yaml
- name: User setup
  ansible.builtin.include_tasks: users.yaml
- name: rpm setup
  ansible.builtin.include_tasks: rpms_airgap.yaml
- name: Shared Store setup
  when: shared_store_endpoint is defined
  ansible.builtin.include_tasks: sharedstore.yaml
- name: Create CA for selfsigned
  when: "ca_certs == 'selfsigned'"
  ansible.builtin.include_tasks: createca.yaml
  run_once: true
- name: Hub install
  ansible.builtin.include_tasks: hub_install.yaml
  when: "'hub' in group_names"
- name: Worker install
  ansible.builtin.include_tasks: worker_install.yaml
  when: "'workers' in group_names"
