- name: Common tasks
  ansible.builtin.include_tasks: reachable.yaml
- name: Update
  ansible.builtin.include_tasks: update.yaml
- name: Common
  ansible.builtin.include_tasks: common.yaml
- name: User setup
  ansible.builtin.include_tasks: users.yaml
- name: RPM setup
  ansible.builtin.include_tasks: rpms.yaml
- name: Shared Store setup
  when: shared_store_endpoint is defined
  ansible.builtin.include_tasks: sharedstore.yaml
- name: Create CA for selfsigned
  when: "ca_certs == 'selfsigned'"
  ansible.builtin.include_tasks: createca.yaml
  run_once: true
