- hosts: all
  become: yes
  vars_files:
    - vars/ldap.yaml
    - vars/common.yaml
    - vars/license.yaml
  vars:
    bootstrap_params: "{{ '--nointernaltls' if ca_certs != 'internal' else ''}}"
  tasks:
  - name: Install tasks
    ansible.builtin.include_tasks: install_tasks.yaml
  - name: Configure tasks
    ansible.builtin.include_tasks: configure_tasks.yaml
