- name: Make rpms dir
  file:
    path: "{{ rpmsdirectory }}"
    state: directory

- name: Copy rpms
  ansible.builtin.copy:
    src: "{{ (rpms_source_dir | default('hubrpms')) }}/{{ item }}"
    dest: "{{ rpmsdirectory }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - "{{ airgapped.hub_rpm_file }}"
  when: "'hub' in group_names"

- name: Copy SLC rpm
  ansible.builtin.copy:
    src: "{{ (rpms_source_dir | default('hubrpms')) }}/{{ item }}"
    dest: "{{ rpmsdirectory }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - "{{ airgapped.slc_rpm_file }}"
  when: "'workers' in group_names"

- name: Copy worker rpm
  ansible.builtin.copy:
    src: "{{ (rpms_source_dir | default('hubrpms')) }}/{{ item }}"
    dest: "{{ rpmsdirectory }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - "{{ airgapped.worker_rpm_file }}"
  when: "'workers' in group_names"

- name: Install hub and worker RPMs from disk
  ansible.builtin.yum:
    name: "{{ rpmsdirectory }}/{{ item }}"
    state: present
    disable_gpg_check: yes
  loop:
    - "{{ airgapped.hub_rpm_file }}"
  when: "'hub' in group_names"

- name: Install SLC RPM from disk (workers only)
  ansible.builtin.yum:
    name: "{{ rpmsdirectory }}/{{ item }}"
    state: present
    disable_gpg_check: yes
  loop:
    - "{{ airgapped.slc_rpm_file }}"
  when: "'workers' in group_names"

- name: Install worker RPM from disk (workers only)
  ansible.builtin.yum:
    name: "{{ rpmsdirectory }}/{{ item }}"
    state: present
    disable_gpg_check: yes
  loop:
    - "{{ airgapped.worker_rpm_file }}"
  when: "'workers' in group_names"
